<?php
/** @package Processos::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProcessoMap.php");

/**
 * ProcessoDAO provides object-oriented access to the processo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Processos::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProcessoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $DataEntrada;

	/** @var string */
	public $Numero;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Assunto;

	/** @var date */
	public $DataSaida;

	/** @var string */
	public $Observacao;

	/** @var int */
	public $SetorId;


	/**
	 * Returns the foreign object based on the value of SetorId
	 * @return Setor
	 */
	public function GetSetor()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_processo_setor");
	}


}
?>