<?php
/** @package Processos::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("RoleMap.php");

/**
 * RoleDAO provides object-oriented access to the role table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Processos::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class RoleDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Role;

	/** @var date */
	public $Created;

	/** @var date */
	public $Modified;


	/**
	 * Returns a dataset of User objects with matching RoleId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUsers($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_users_roles1", $criteria);
	}


}
?>