<?php
/** @package Processos::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SetorMap.php");

/**
 * SetorDAO provides object-oriented access to the setor table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Processos::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SetorDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;


	/**
	 * Returns a dataset of Processo objects with matching SetorId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProcessos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_processo_setor", $criteria);
	}


}
?>